name: Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this solve? What are you trying to do that isn't currently possible or is harder than it should be?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: How would you like this to work? Include CLI examples, API usage, or workflow descriptions if applicable.
    validations:
      required: true
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Pipeline / agents
        - Reference dataset
        - MCP server
        - CLI
        - Python API
        - Evaluation
        - New provider support (OpenAI, Anthropic, local models, etc.)
        - Documentation
        - Other
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you've thought about.
    validations:
      required: false
  - type: checkboxes
    id: contribution
    attributes:
      label: Willingness to contribute
      options:
        - label: I'd be willing to submit a PR for this feature
